// Textos propios de la hoja "Mes" en los tres idiomas. Los comunes (Add, Delete, Date, Amount, Currency, Rate,
// Account, From, To, Received, Month rates, Delete month, Income, "Close {month}", "{month} summary"…) salen del
// diccionario de src/i18n con t(); los nombres de mes, categoría y método y el origen de una tasa, de useI18n().
// Los códigos de moneda (DOP, USD, TRY) se ven igual en todos los idiomas.
//
// El español es el de la versión 1, tal cual. El turco usa los términos acordados y los del libro de Excel
// (Kalem, Kanal, İşlem geçmişi…); queda pendiente la revisión de un hablante nativo.
//
// Las metas de las tarjetas terminan en "· total" porque detrás va la cifra, que se pinta aparte (<Num>).
// Las etiquetas "… de {name}" son nombres accesibles de celdas; en turco van como "Etiqueta: {name}" porque el
// nombre lo escribe el usuario y no se puede declinar.

import { defineStrings } from '../../i18n';

export const MES = defineStrings({
  en: {
    // Gastos mensuales
    fixedTitle: 'Monthly expenses',
    fixedMeta: '{paid} of {total} paid · total',
    paid: 'Paid',
    item: 'Item',
    day: 'Day',
    newFixed: 'New monthly expense',
    newFixedDay: 'Day of the new expense',
    newFixedAmount: 'Amount of the new expense',
    newFixedCurrency: 'Currency of the new expense',
    paidNamed: 'Paid: {name}',
    dayOf: 'Day of {name}',
    amountOf: 'Amount of {name}',
    currencyOf: 'Currency of {name}',
    newFixedAccount: 'Account of the new expense',
    addFixed: 'Add expense',
    accountOf: 'Account of {name}',
    payWith: 'Pay with',
    payWithAccount: 'Account',
    payWithCard: 'Card',
    payWithOf: 'Pay with of {name}',
    newFixedPayWith: 'How the new expense is paid',
    cardName: 'Credit card',
    cardTag: 'from card',
    cardTitle: 'What is owed on the card: the previous balance, the other charges you type and everything charged to it this month. Paying it charges the budget and the paying account.',
    cardDetail: 'prev {prev} · other {other} · charged {charged}',
    cardPaidOf: 'paid {paid} of {total} · left {left}',
    cardOther: 'Other charges on the credit card',
    payCardTitle: 'Pay credit card',
    payCardTotal: 'Total owed: {total} {currency}',
    payCardPaid: 'Already paid: {paid} {currency}',
    payCardLeft: 'Left: {left} {currency}',
    payCardPayments: 'Payments made',
    payCardRemove: 'Remove payment of {amount} {currency} from {account} on {date}',
    payCardClose: 'Close',
    payCardBody: 'What you leave unpaid stays pending this month; if the month closes with it unpaid it carries over to the next one.',
    payCardAmount: 'Amount ({currency})',
    payCardAccount: 'Paid from',
    payCardRest: 'Left: {rest} {currency}',
    payCardInvalid: 'Enter an amount greater than 0 and no more than what is left.',
    payCardConfirm: 'Confirm',

    // Por categoría
    byCategory: 'By category',
    noExpenses: 'No expenses yet this month.',

    // Envíos
    transfersTitle: 'Transfers',
    via: 'Via',
    deleteTransfer: 'Delete transfer from {date}',
    newTransferDate: 'Date of the new transfer',
    newTransferVia: 'Via of the new transfer',
    newTransferFrom: 'Account the new transfer leaves from',
    newTransferAmount: 'Amount of the new transfer',
    newTransferTo: 'Account the new transfer goes to',
    newTransferRate: 'Rate of the new transfer',
    viaOf: 'Via of {name}',
    fromOf: 'Account {name} leaves from',
    toOf: 'Account {name} goes to',
    rateOf: 'Rate of {name}',
    transferBudgetOf: 'Moves budget: {name}',
    newTransferBudget: 'The new transfer moves budget',
    transfersNote:
      'Money moved between your accounts. With "Moves budget" checked, this month\'s budget moves with it: it leaves the origin account\'s part and joins the destination\'s. The fee is charged to the origin account and counts as a transaction.',
    feeOf: 'Fee of {name}',
    newTransferFee: 'Fee of the new transfer',
    addTransfer: 'Add transfer',

    // Tasas del mes
    pairRate: 'Rate {from} → {to}',
    newRateFrom: 'Currency the new rate converts from',
    newRateTo: 'Currency the new rate converts to',
    newRate: 'New rate',
    rateSince: 'Since',
    ratesNote: 'A new rate applies from its date on. Earlier transactions keep the rate they had.',
    pairRateSince: 'Rate {from} → {to} since {date}',
    deleteRateSince: 'Delete rate {from} → {to} of {date}',
    newRateDate: 'Date the new rate applies from',
    
    // Ingresos del mes
    incomeNote: 'Money received outside transfers. With "Adds to budget" checked, it also raises this month\'s budget.',

    // Historial
    txTitle: 'Transaction history',
    txMeta: { one: '{count} transaction · total', other: '{count} transactions · total' },
    description: 'Name',
    place: 'Place',
    category: 'Category',
    method: 'Method',
    notes: 'Description',
    newTx: 'New transaction',
    notesOptional: 'Description (optional)',
    newTxDate: 'Date of the new transaction',
    newTxPlace: 'Place of the new transaction',
    newTxCategory: 'Category of the new transaction',
    newTxMethod: 'Method of the new transaction',
    newTxAmount: 'Amount of the new transaction',
    newTxCurrency: 'Currency of the new transaction',
    newTxAccount: 'Account of the new transaction',
    newTxNotes: 'Description of the new transaction',
    dateOf: 'Date of {name}',
    placeOf: 'Place of {name}',
    categoryOf: 'Category of {name}',
    methodOf: 'Method of {name}',
    notesOf: 'Description of {name}',
    openNotes: 'Open the description of {name}',
    closeNotes: 'Close',
    addTx: 'Add transaction',
    // La comisión de un envío, como fila del historial: su nombre y la marca de que sale del envío.
    feeName: '{via} fee',
    feeFromTransfer: 'From the transfer of {date}. Change it in Transfers.',
    feeTag: 'from transfer',

    // Fuera de presupuesto
    outsideTitle: 'Outside budget',
    outsideMeta: { one: '{count} expense · total', other: '{count} expenses · total' },
    outsideNote: 'Paid from your accounts like any expense, but not part of the budget: it does not count as used or available.',
    addOutside: 'Add outside-budget expense',
    newOutside: 'New outside-budget expense',
    newOutsideDate: 'Date of the new outside-budget expense',
    newOutsideAccount: 'Account of the new outside-budget expense',
    newOutsideAmount: 'Amount of the new outside-budget expense',
    newOutsideCurrency: 'Currency of the new outside-budget expense',
    newOutsideNotes: 'Description of the new outside-budget expense',
    moveOutside: 'Move {name} outside the budget',
    moveToBudget: 'Move {name} back to the budget',

    // Cerrar el mes y mes cerrado
    closeText: 'Closing the month saves this summary and creates {next} with the same monthly expenses, not marked as paid.',
    closedNote: 'Month closed. Records are read-only.',
    amountsIn: 'Amounts in {currency}',
    spent: 'Spent',
    saved: 'Saved',
    vsBudget: 'Vs. budget',
    reopen: 'Reopen month',
  },

  es: {
    fixedTitle: 'Gastos mensuales',
    fixedMeta: '{paid} de {total} pagados · total',
    paid: 'Pagado',
    item: 'Concepto',
    day: 'Día',
    newFixed: 'Nuevo gasto mensual',
    newFixedDay: 'Día del nuevo gasto',
    newFixedAmount: 'Monto del nuevo gasto',
    newFixedCurrency: 'Moneda del nuevo gasto',
    paidNamed: 'Pagado: {name}',
    dayOf: 'Día de {name}',
    amountOf: 'Monto de {name}',
    currencyOf: 'Moneda de {name}',
    newFixedAccount: 'Cuenta del nuevo gasto',
    addFixed: 'Agregar gasto',
    accountOf: 'Cuenta de {name}',
    payWith: 'Pagar con',
    payWithAccount: 'Cuenta',
    payWithCard: 'Tarjeta',
    payWithOf: 'Forma de pago de {name}',
    newFixedPayWith: 'Cómo se paga el nuevo gasto',
    cardName: 'Tarjeta de crédito',
    cardTag: 'de la tarjeta',
    cardTitle: 'Lo que se debe a la tarjeta: el saldo anterior, los otros cargos que escribes y todo lo cargado este mes. Al pagarla se descuenta del presupuesto y de la cuenta que paga.',
    cardDetail: 'ant. {prev} · otros {other} · cargado {charged}',
    cardPaidOf: 'pagado {paid} de {total} · falta {left}',
    cardOther: 'Otros cargos de la tarjeta de crédito',
    payCardTitle: 'Pagar la tarjeta de crédito',
    payCardTotal: 'Total adeudado: {total} {currency}',
    payCardPaid: 'Ya pagado: {paid} {currency}',
    payCardLeft: 'Falta: {left} {currency}',
    payCardPayments: 'Pagos hechos',
    payCardRemove: 'Quitar el pago de {amount} {currency} desde {account} del {date}',
    payCardClose: 'Cerrar',
    payCardBody: 'Lo que dejes sin pagar queda pendiente este mes; si el mes se cierra sin pagarlo, pasa al siguiente.',
    payCardAmount: 'Monto ({currency})',
    payCardAccount: 'Se paga desde',
    payCardRest: 'Falta: {rest} {currency}',
    payCardInvalid: 'Escribe un monto mayor que 0 y que no pase de lo que falta.',
    payCardConfirm: 'Confirmar',

    byCategory: 'Por categoría',
    noExpenses: 'Aún no hay gastos este mes.',

    transfersTitle: 'Envíos',
    via: 'Vía',
    deleteTransfer: 'Eliminar envío del {date}',
    newTransferDate: 'Fecha del nuevo envío',
    newTransferVia: 'Vía del nuevo envío',
    newTransferFrom: 'Cuenta de la que sale el nuevo envío',
    newTransferAmount: 'Monto del nuevo envío',
    newTransferTo: 'Cuenta a la que llega el nuevo envío',
    newTransferRate: 'Tasa del nuevo envío',
    viaOf: 'Vía de {name}',
    fromOf: 'Cuenta de la que sale {name}',
    toOf: 'Cuenta a la que llega {name}',
    rateOf: 'Tasa de {name}',
    transferBudgetOf: 'Mueve presupuesto: {name}',
    newTransferBudget: 'El nuevo envío mueve presupuesto',
    transfersNote:
      'Dinero que pasa de una cuenta tuya a otra. Con «Mueve presupuesto» marcado, el presupuesto de este mes se mueve con él: sale de la parte de la cuenta de origen y pasa a la de destino. La comisión se cobra de la cuenta de origen y cuenta como una transacción.',
    feeOf: 'Comisión de {name}',
    newTransferFee: 'Comisión del nuevo envío',
    addTransfer: 'Agregar envío',

    pairRate: 'Tasa {from} → {to}',
    newRateFrom: 'Moneda de origen de la nueva tasa',
    newRateTo: 'Moneda de destino de la nueva tasa',
    newRate: 'Nueva tasa',
    rateSince: 'Vigente desde',
    ratesNote: 'Una tasa nueva vale desde su fecha. Las transacciones anteriores conservan la que tenían.',
    pairRateSince: 'Tasa {from} → {to} desde el {date}',
    deleteRateSince: 'Eliminar tasa {from} → {to} del {date}',
    newRateDate: 'Fecha desde la que vale la tasa nueva',
    
    incomeNote: 'Dinero recibido fuera de los envíos. Con «Suma al presupuesto» marcado, sube además el presupuesto de este mes.',

    txTitle: 'Historial de transacciones',
    txMeta: { one: '{count} transacción · total', other: '{count} transacciones · total' },
    description: 'Nombre',
    place: 'Lugar',
    category: 'Categoría',
    method: 'Método',
    notes: 'Descripción',
    newTx: 'Nueva transacción',
    notesOptional: 'Descripción (opcional)',
    newTxDate: 'Fecha de la nueva transacción',
    newTxPlace: 'Lugar de la nueva transacción',
    newTxCategory: 'Categoría de la nueva transacción',
    newTxMethod: 'Método de la nueva transacción',
    newTxAmount: 'Monto de la nueva transacción',
    newTxCurrency: 'Moneda de la nueva transacción',
    newTxAccount: 'Cuenta de la nueva transacción',
    newTxNotes: 'Descripción de la nueva transacción',
    dateOf: 'Fecha de {name}',
    placeOf: 'Lugar de {name}',
    categoryOf: 'Categoría de {name}',
    methodOf: 'Método de {name}',
    notesOf: 'Descripción de {name}',
    openNotes: 'Abrir la descripción de {name}',
    closeNotes: 'Cerrar',
    addTx: 'Agregar transacción',
    feeName: 'Comisión de {via}',
    feeFromTransfer: 'Sale del envío del {date}. Se cambia en Envíos.',
    feeTag: 'del envío',

    outsideTitle: 'Fuera de presupuesto',
    outsideMeta: { one: '{count} gasto · total', other: '{count} gastos · total' },
    outsideNote: 'Se paga de tus cuentas como cualquier gasto, pero no es parte del presupuesto: no cuenta como usado ni como disponible.',
    addOutside: 'Agregar gasto fuera de presupuesto',
    newOutside: 'Nuevo gasto fuera de presupuesto',
    newOutsideDate: 'Fecha del nuevo gasto fuera de presupuesto',
    newOutsideAccount: 'Cuenta del nuevo gasto fuera de presupuesto',
    newOutsideAmount: 'Monto del nuevo gasto fuera de presupuesto',
    newOutsideCurrency: 'Moneda del nuevo gasto fuera de presupuesto',
    newOutsideNotes: 'Descripción del nuevo gasto fuera de presupuesto',
    moveOutside: 'Mover {name} fuera del presupuesto',
    moveToBudget: 'Devolver {name} al presupuesto',

    closeText: 'Al cerrar el mes se guarda este resumen y se crea {next} con los mismos gastos mensuales, sin marcar como pagados.',
    closedNote: 'Mes cerrado. Los registros quedan de solo lectura.',
    amountsIn: 'Importes en {currency}',
    spent: 'Gastado',
    saved: 'Ahorrado',
    vsBudget: 'Vs. presupuesto',
    reopen: 'Reabrir mes',
  },

  tr: {
    fixedTitle: 'Aylık giderler',
    fixedMeta: '{paid} / {total} ödendi · toplam',
    paid: 'Ödendi',
    item: 'Kalem',
    day: 'Gün',
    newFixed: 'Yeni aylık gider',
    newFixedDay: 'Yeni giderin günü',
    newFixedAmount: 'Yeni giderin tutarı',
    newFixedCurrency: 'Yeni giderin para birimi',
    paidNamed: 'Ödendi: {name}',
    dayOf: 'Gün: {name}',
    amountOf: 'Tutar: {name}',
    currencyOf: 'Para birimi: {name}',
    newFixedAccount: 'Yeni giderin hesabı',
    addFixed: 'Gider ekle',
    accountOf: 'Hesap: {name}',
    payWith: 'Ödeme şekli',
    payWithAccount: 'Hesap',
    payWithCard: 'Kart',
    payWithOf: 'Ödeme şekli: {name}',
    newFixedPayWith: 'Yeni giderin ödeme şekli',
    cardName: 'Kredi kartı',
    cardTag: 'karttan',
    cardTitle: 'Karta borç: önceki bakiye, yazdığınız diğer harcamalar ve bu ay karta yüklenen her şey. Ödendiğinde bütçeden ve ödeyen hesaptan düşer.',
    cardDetail: 'önceki {prev} · diğer {other} · yüklenen {charged}',
    cardPaidOf: '{total} borcun {paid} tutarı ödendi · kalan {left}',
    cardOther: 'Kredi kartının diğer harcamaları',
    payCardTitle: 'Kredi kartını öde',
    payCardTotal: 'Toplam borç: {total} {currency}',
    payCardPaid: 'Ödenen: {paid} {currency}',
    payCardLeft: 'Kalan: {left} {currency}',
    payCardPayments: 'Yapılan ödemeler',
    payCardRemove: '{date} tarihli {account} hesabından {amount} {currency} ödemesini kaldır',
    payCardClose: 'Kapat',
    payCardBody: 'Ödemediğiniz tutar bu ay beklemede kalır; ay ödenmeden kapanırsa bir sonraki aya geçer.',
    payCardAmount: 'Tutar ({currency})',
    payCardAccount: 'Ödenen hesap',
    payCardRest: 'Kalan: {rest} {currency}',
    payCardInvalid: '0’dan büyük ve kalan tutarı geçmeyen bir tutar girin.',
    payCardConfirm: 'Onayla',

    byCategory: 'Kategoriye göre',
    noExpenses: 'Bu ay henüz gider yok.',

    transfersTitle: 'Transferler',
    via: 'Kanal',
    deleteTransfer: '{date} tarihli transferi sil',
    newTransferDate: 'Yeni transferin tarihi',
    newTransferVia: 'Yeni transferin kanalı',
    newTransferFrom: 'Yeni transferin çıktığı hesap',
    newTransferAmount: 'Yeni transferin tutarı',
    newTransferTo: 'Yeni transferin gittiği hesap',
    newTransferRate: 'Yeni transferin kuru',
    viaOf: 'Kanal: {name}',
    fromOf: 'Çıkış hesabı: {name}',
    toOf: 'Varış hesabı: {name}',
    rateOf: 'Kur: {name}',
    transferBudgetOf: 'Bütçeyi taşır: {name}',
    newTransferBudget: 'Yeni transfer bütçeyi taşır',
    transfersNote:
      'Hesaplarınız arasında aktarılan para. "Bütçeyi taşır" işaretliyse bu ayın bütçesi de onunla taşınır: çıkış hesabının payından düşer, varış hesabının payına eklenir. Komisyon çıkış hesabından alınır ve bir işlem olarak sayılır.',
    feeOf: 'Komisyon: {name}',
    newTransferFee: 'Yeni transferin komisyonu',
    addTransfer: 'Transfer ekle',

    pairRate: 'Kur {from} → {to}',
    newRateFrom: 'Yeni kurun kaynak para birimi',
    newRateTo: 'Yeni kurun hedef para birimi',
    newRate: 'Yeni kur',
    rateSince: 'Başlangıç',
    ratesNote: 'Yeni kur, tarihinden itibaren geçerlidir. Önceki işlemler kendi kurunu korur.',
    pairRateSince: 'Kur {from} → {to}, {date} tarihinden itibaren',
    deleteRateSince: 'Kuru sil: {from} → {to}, {date}',
    newRateDate: 'Yeni kurun geçerli olacağı tarih',
    
    incomeNote: 'Transferler dışında alınan para. "Bütçeye eklenir" işaretliyse bu ayın bütçesini de artırır.',

    txTitle: 'İşlem geçmişi',
    txMeta: { one: '{count} işlem · toplam', other: '{count} işlem · toplam' },
    description: 'Ad',
    place: 'Yer',
    category: 'Kategori',
    method: 'Yöntem',
    notes: 'Açıklama',
    newTx: 'Yeni işlem',
    notesOptional: 'Açıklama (isteğe bağlı)',
    newTxDate: 'Yeni işlemin tarihi',
    newTxPlace: 'Yeni işlemin yeri',
    newTxCategory: 'Yeni işlemin kategorisi',
    newTxMethod: 'Yeni işlemin yöntemi',
    newTxAmount: 'Yeni işlemin tutarı',
    newTxCurrency: 'Yeni işlemin para birimi',
    newTxAccount: 'Yeni işlemin hesabı',
    newTxNotes: 'Yeni işlemin açıklaması',
    dateOf: 'Tarih: {name}',
    placeOf: 'Yer: {name}',
    categoryOf: 'Kategori: {name}',
    methodOf: 'Yöntem: {name}',
    notesOf: 'Açıklama: {name}',
    openNotes: '{name} açıklamasını aç',
    closeNotes: 'Kapat',
    addTx: 'İşlem ekle',
    feeName: '{via} komisyonu',
    feeFromTransfer: '{date} tarihli transferden gelir. Transferler bölümünden değiştirilir.',
    feeTag: 'transferden',

    outsideTitle: 'Bütçe dışı',
    outsideMeta: { one: '{count} gider · toplam', other: '{count} gider · toplam' },
    outsideNote: 'Hesaplarınızdan diğer giderler gibi ödenir ama bütçenin parçası değildir: kullanılan veya kalan tutara sayılmaz.',
    addOutside: 'Bütçe dışı gider ekle',
    newOutside: 'Yeni bütçe dışı gider',
    newOutsideDate: 'Yeni bütçe dışı giderin tarihi',
    newOutsideAccount: 'Yeni bütçe dışı giderin hesabı',
    newOutsideAmount: 'Yeni bütçe dışı giderin tutarı',
    newOutsideCurrency: 'Yeni bütçe dışı giderin para birimi',
    newOutsideNotes: 'Yeni bütçe dışı giderin açıklaması',
    moveOutside: '{name} giderini bütçe dışına taşı',
    moveToBudget: '{name} giderini bütçeye geri taşı',

    closeText: 'Ay kapatıldığında bu özet kaydedilir ve {next}, aynı aylık giderlerle, ödenmemiş olarak oluşturulur.',
    closedNote: 'Ay kapalı. Kayıtlar salt okunur.',
    amountsIn: 'Tutarlar {currency} cinsinden',
    spent: 'Harcanan',
    saved: 'Biriken',
    vsBudget: 'Bütçeye göre',
    reopen: 'Ayı yeniden aç',
  },
});
