// Textos propios de la hoja "Mes" en los tres idiomas. Los comunes (Add, Delete, Date, Amount, Currency, Rate,
// Account, From, To, Received, Month rates, Delete month, Income, "Close {month}", "{month} summary"…) salen del
// diccionario de src/i18n con t(); los nombres de mes, categoría y método y el origen de una tasa, de useI18n().
// Los códigos de moneda (DOP, USD, TRY) se ven igual en todos los idiomas.
//
// El español es el de la versión 1, tal cual. El turco usa los términos acordados y los del libro de Excel
// (Kalem, Kanal, İşlem geçmişi…); queda pendiente la revisión de un hablante nativo.
//
// Las metas de las tarjetas terminan en "· total" porque detrás va la cifra, que se pinta aparte (<Num>).
// Las etiquetas "… de {name}" son nombres accesibles de celdas; en turco van como "Etiqueta: {name}" porque el
// nombre lo escribe el usuario y no se puede declinar.

import { defineStrings } from '../../i18n';

export const MES = defineStrings({
  en: {
    // Gastos mensuales
    fixedTitle: 'Monthly expenses',
    fixedMeta: '{paid} of {total} paid · total',
    paid: 'Paid',
    item: 'Item',
    day: 'Day',
    newFixed: 'New monthly expense',
    newFixedDay: 'Day of the new expense',
    newFixedAmount: 'Amount of the new expense',
    newFixedCurrency: 'Currency of the new expense',
    paidNamed: 'Paid: {name}',
    dayOf: 'Day of {name}',
    amountOf: 'Amount of {name}',
    currencyOf: 'Currency of {name}',
    newFixedAccount: 'Account of the new expense',
    accountOf: 'Account of {name}',

    // Por categoría
    byCategory: 'By category',
    noExpenses: 'No expenses yet this month.',

    // Envíos
    transfersTitle: 'Transfers',
    via: 'Via',
    deleteTransfer: 'Delete transfer from {date}',
    newTransferDate: 'Date of the new transfer',
    newTransferVia: 'Via of the new transfer',
    newTransferFrom: 'Account the new transfer leaves from',
    newTransferAmount: 'Amount of the new transfer',
    newTransferTo: 'Account the new transfer goes to',
    newTransferRate: 'Rate of the new transfer',
    viaOf: 'Via of {name}',
    fromOf: 'Account {name} leaves from',
    toOf: 'Account {name} goes to',
    rateOf: 'Rate of {name}',

    // Tasas del mes
    pairRate: 'Rate {from} → {to}',
    deleteRate: 'Delete rate {from} → {to}',
    newRateFrom: 'Currency the new rate converts from',
    newRateTo: 'Currency the new rate converts to',
    newRate: 'New rate',

    // Historial
    txTitle: 'Transaction history',
    txMeta: { one: '{count} transaction · total', other: '{count} transactions · total' },
    description: 'Name',
    place: 'Place',
    category: 'Category',
    method: 'Method',
    notes: 'Description',
    newTx: 'New transaction',
    notesOptional: 'Description (optional)',
    newTxDate: 'Date of the new transaction',
    newTxPlace: 'Place of the new transaction',
    newTxCategory: 'Category of the new transaction',
    newTxMethod: 'Method of the new transaction',
    newTxAmount: 'Amount of the new transaction',
    newTxCurrency: 'Currency of the new transaction',
    newTxAccount: 'Account of the new transaction',
    newTxNotes: 'Description of the new transaction',
    dateOf: 'Date of {name}',
    placeOf: 'Place of {name}',
    categoryOf: 'Category of {name}',
    methodOf: 'Method of {name}',
    notesOf: 'Description of {name}',
    openNotes: 'Open the description of {name}',
    closeNotes: 'Close',

    // Cerrar el mes y mes cerrado
    closeText: 'Closing the month saves this summary and creates {next} with the same monthly expenses, not marked as paid.',
    closedNote: 'Month closed. Records are read-only.',
    amountsIn: 'Amounts in {currency}',
    spent: 'Spent',
    saved: 'Saved',
    vsBudget: 'Vs. budget',
    reopen: 'Reopen month',
  },

  es: {
    fixedTitle: 'Gastos mensuales',
    fixedMeta: '{paid} de {total} pagados · total',
    paid: 'Pagado',
    item: 'Concepto',
    day: 'Día',
    newFixed: 'Nuevo gasto mensual',
    newFixedDay: 'Día del nuevo gasto',
    newFixedAmount: 'Monto del nuevo gasto',
    newFixedCurrency: 'Moneda del nuevo gasto',
    paidNamed: 'Pagado: {name}',
    dayOf: 'Día de {name}',
    amountOf: 'Monto de {name}',
    currencyOf: 'Moneda de {name}',
    newFixedAccount: 'Cuenta del nuevo gasto',
    accountOf: 'Cuenta de {name}',

    byCategory: 'Por categoría',
    noExpenses: 'Aún no hay gastos este mes.',

    transfersTitle: 'Envíos',
    via: 'Vía',
    deleteTransfer: 'Eliminar envío del {date}',
    newTransferDate: 'Fecha del nuevo envío',
    newTransferVia: 'Vía del nuevo envío',
    newTransferFrom: 'Cuenta de la que sale el nuevo envío',
    newTransferAmount: 'Monto del nuevo envío',
    newTransferTo: 'Cuenta a la que llega el nuevo envío',
    newTransferRate: 'Tasa del nuevo envío',
    viaOf: 'Vía de {name}',
    fromOf: 'Cuenta de la que sale {name}',
    toOf: 'Cuenta a la que llega {name}',
    rateOf: 'Tasa de {name}',

    pairRate: 'Tasa {from} → {to}',
    deleteRate: 'Eliminar tasa {from} → {to}',
    newRateFrom: 'Moneda de origen de la nueva tasa',
    newRateTo: 'Moneda de destino de la nueva tasa',
    newRate: 'Nueva tasa',

    txTitle: 'Historial de transacciones',
    txMeta: { one: '{count} transacción · total', other: '{count} transacciones · total' },
    description: 'Nombre',
    place: 'Lugar',
    category: 'Categoría',
    method: 'Método',
    notes: 'Descripción',
    newTx: 'Nueva transacción',
    notesOptional: 'Descripción (opcional)',
    newTxDate: 'Fecha de la nueva transacción',
    newTxPlace: 'Lugar de la nueva transacción',
    newTxCategory: 'Categoría de la nueva transacción',
    newTxMethod: 'Método de la nueva transacción',
    newTxAmount: 'Monto de la nueva transacción',
    newTxCurrency: 'Moneda de la nueva transacción',
    newTxAccount: 'Cuenta de la nueva transacción',
    newTxNotes: 'Descripción de la nueva transacción',
    dateOf: 'Fecha de {name}',
    placeOf: 'Lugar de {name}',
    categoryOf: 'Categoría de {name}',
    methodOf: 'Método de {name}',
    notesOf: 'Descripción de {name}',
    openNotes: 'Abrir la descripción de {name}',
    closeNotes: 'Cerrar',

    closeText: 'Al cerrar el mes se guarda este resumen y se crea {next} con los mismos gastos mensuales, sin marcar como pagados.',
    closedNote: 'Mes cerrado. Los registros quedan de solo lectura.',
    amountsIn: 'Importes en {currency}',
    spent: 'Gastado',
    saved: 'Ahorrado',
    vsBudget: 'Vs. presupuesto',
    reopen: 'Reabrir mes',
  },

  tr: {
    fixedTitle: 'Aylık giderler',
    fixedMeta: '{paid} / {total} ödendi · toplam',
    paid: 'Ödendi',
    item: 'Kalem',
    day: 'Gün',
    newFixed: 'Yeni aylık gider',
    newFixedDay: 'Yeni giderin günü',
    newFixedAmount: 'Yeni giderin tutarı',
    newFixedCurrency: 'Yeni giderin para birimi',
    paidNamed: 'Ödendi: {name}',
    dayOf: 'Gün: {name}',
    amountOf: 'Tutar: {name}',
    currencyOf: 'Para birimi: {name}',
    newFixedAccount: 'Yeni giderin hesabı',
    accountOf: 'Hesap: {name}',

    byCategory: 'Kategoriye göre',
    noExpenses: 'Bu ay henüz gider yok.',

    transfersTitle: 'Transferler',
    via: 'Kanal',
    deleteTransfer: '{date} tarihli transferi sil',
    newTransferDate: 'Yeni transferin tarihi',
    newTransferVia: 'Yeni transferin kanalı',
    newTransferFrom: 'Yeni transferin çıktığı hesap',
    newTransferAmount: 'Yeni transferin tutarı',
    newTransferTo: 'Yeni transferin gittiği hesap',
    newTransferRate: 'Yeni transferin kuru',
    viaOf: 'Kanal: {name}',
    fromOf: 'Çıkış hesabı: {name}',
    toOf: 'Varış hesabı: {name}',
    rateOf: 'Kur: {name}',

    pairRate: 'Kur {from} → {to}',
    deleteRate: '{from} → {to} kurunu sil',
    newRateFrom: 'Yeni kurun kaynak para birimi',
    newRateTo: 'Yeni kurun hedef para birimi',
    newRate: 'Yeni kur',

    txTitle: 'İşlem geçmişi',
    txMeta: { one: '{count} işlem · toplam', other: '{count} işlem · toplam' },
    description: 'Ad',
    place: 'Yer',
    category: 'Kategori',
    method: 'Yöntem',
    notes: 'Açıklama',
    newTx: 'Yeni işlem',
    notesOptional: 'Açıklama (isteğe bağlı)',
    newTxDate: 'Yeni işlemin tarihi',
    newTxPlace: 'Yeni işlemin yeri',
    newTxCategory: 'Yeni işlemin kategorisi',
    newTxMethod: 'Yeni işlemin yöntemi',
    newTxAmount: 'Yeni işlemin tutarı',
    newTxCurrency: 'Yeni işlemin para birimi',
    newTxAccount: 'Yeni işlemin hesabı',
    newTxNotes: 'Yeni işlemin açıklaması',
    dateOf: 'Tarih: {name}',
    placeOf: 'Yer: {name}',
    categoryOf: 'Kategori: {name}',
    methodOf: 'Yöntem: {name}',
    notesOf: 'Açıklama: {name}',
    openNotes: '{name} açıklamasını aç',
    closeNotes: 'Kapat',

    closeText: 'Ay kapatıldığında bu özet kaydedilir ve {next}, aynı aylık giderlerle, ödenmemiş olarak oluşturulur.',
    closedNote: 'Ay kapalı. Kayıtlar salt okunur.',
    amountsIn: 'Tutarlar {currency} cinsinden',
    spent: 'Harcanan',
    saved: 'Biriken',
    vsBudget: 'Bütçeye göre',
    reopen: 'Ayı yeniden aç',
  },
});
